# Generated by Django 3.2.3 on 2021-07-14 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date Evolved')),
                ('evolution', models.CharField(choices=[('1st', 'First Evolution'), ('2nd', 'Second Evolution'), ('3rd', 'Third Evolution')], default='1st', max_length=3, verbose_name='Evolution Time')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.pokemon')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
