# Generated by Django 3.2.3 on 2021-07-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_evolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolution',
            name='evolution',
            field=models.CharField(choices=[('1st', 'First Evolution'), ('2nd', 'Second Evolution'), ('3rd', 'Mega Evolution')], default='1st', max_length=3, verbose_name='Evolution Time'),
        ),
    ]
