# Generated by Django 3.2.3 on 2021-07-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_evolution_evolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='attacks',
            field=models.ManyToManyField(to='main_app.Attack'),
        ),
    ]
